Open Watcom Make Version 1.3
Portions Copyright (c) 1988-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
	wlink @SDLTTF
Open Watcom Linker Version 1.3
Portions Copyright (c) 1985-2002 Sybase, Inc. All Rights Reserved.
Source code is available under the Sybase Open Watcom Public License.
See http://www.openwatcom.org/ for details.
loading object files
Warning! W1027: file freetype-2.1.9\objs\autofit.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\autofit\autofit.c): redefinition of af_autofitter_service ignored
Warning! W1027: file freetype-2.1.9\objs\autofit.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\autofit\autofit.c): redefinition of autofit_module_class ignored
Warning! W1027: file freetype-2.1.9\objs\autohint.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\autohint\autohint.c): redefinition of ah_arctan ignored
Warning! W1027: file freetype-2.1.9\objs\autohint.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\autohint\autohint.c): redefinition of ft_autohinter_service ignored
Warning! W1027: file freetype-2.1.9\objs\autohint.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\autohint\autohint.c): redefinition of autohint_module_class ignored
Warning! W1027: file freetype-2.1.9\objs\bdfdrivr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\bdf\bdfdrivr.c): redefinition of bdf_cmap_class ignored
Warning! W1027: file freetype-2.1.9\objs\bdfdrivr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\bdf\bdfdrivr.c): redefinition of bdf_driver_class ignored
Warning! W1027: file freetype-2.1.9\objs\cffcmap.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cff\cffcmap.c): redefinition of cff_cmap_encoding_class_rec ignored
Warning! W1027: file freetype-2.1.9\objs\cffcmap.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cff\cffcmap.c): redefinition of cff_cmap_unicode_class_rec ignored
Warning! W1027: file freetype-2.1.9\objs\cffdrivr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cff\cffdrivr.c): redefinition of cff_driver_class ignored
Warning! W1027: file freetype-2.1.9\objs\ftcalc.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftcalc.c): redefinition of FT_RoundFix ignored
Warning! W1027: file freetype-2.1.9\objs\ftcalc.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftcalc.c): redefinition of FT_CeilFix ignored
Warning! W1027: file freetype-2.1.9\objs\ftcalc.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftcalc.c): redefinition of FT_FloorFix ignored
Warning! W1027: file freetype-2.1.9\objs\ftcalc.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftcalc.c): redefinition of FT_Sqrt32 ignored
Warning! W1027: file freetype-2.1.9\objs\ftcalc.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftcalc.c): redefinition of FT_Add64 ignored
Warning! W1027: file freetype-2.1.9\objs\ftcalc.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftcalc.c): redefinition of FT_MulDiv ignored
Warning! W1027: file freetype-2.1.9\objs\ftcalc.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftcalc.c): redefinition of FT_MulFix ignored
Warning! W1027: file freetype-2.1.9\objs\ftcalc.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftcalc.c): redefinition of FT_DivFix ignored
Warning! W1027: file freetype-2.1.9\objs\ftcalc.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftcalc.c): redefinition of FT_MulTo64 ignored
Warning! W1027: file freetype-2.1.9\objs\ftcalc.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftcalc.c): redefinition of FT_Div64by32 ignored
Warning! W1027: file freetype-2.1.9\objs\ftcalc.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftcalc.c): redefinition of FT_SqrtFixed ignored
Warning! W1027: file freetype-2.1.9\objs\ftcbasic.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcbasic.c): redefinition of FTC_ImageCache_New ignored
Warning! W1027: file freetype-2.1.9\objs\ftcbasic.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcbasic.c): redefinition of FTC_ImageCache_Lookup ignored
Warning! W1027: file freetype-2.1.9\objs\ftcbasic.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcbasic.c): redefinition of FTC_SBitCache_New ignored
Warning! W1027: file freetype-2.1.9\objs\ftcbasic.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcbasic.c): redefinition of FTC_SBitCache_Lookup ignored
Warning! W1027: file freetype-2.1.9\objs\ftcbasic.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcbasic.c): redefinition of ftc_basic_image_family_class ignored
Warning! W1027: file freetype-2.1.9\objs\ftcbasic.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcbasic.c): redefinition of ftc_basic_image_cache_class ignored
Warning! W1027: file freetype-2.1.9\objs\ftcbasic.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcbasic.c): redefinition of ftc_basic_sbit_family_class ignored
Warning! W1027: file freetype-2.1.9\objs\ftcbasic.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcbasic.c): redefinition of ftc_basic_sbit_cache_class ignored
Warning! W1027: file freetype-2.1.9\objs\ftccache.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftccache.c): redefinition of ftc_node_destroy ignored
Warning! W1027: file freetype-2.1.9\objs\ftccache.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftccache.c): redefinition of FTC_Cache_Init ignored
Warning! W1027: file freetype-2.1.9\objs\ftccache.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftccache.c): redefinition of FTC_Cache_Clear ignored
Warning! W1027: file freetype-2.1.9\objs\ftccache.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftccache.c): redefinition of FTC_Cache_Done ignored
Warning! W1027: file freetype-2.1.9\objs\ftccache.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftccache.c): redefinition of FTC_Cache_NewNode ignored
Warning! W1027: file freetype-2.1.9\objs\ftccache.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftccache.c): redefinition of FTC_Cache_Lookup ignored
Warning! W1027: file freetype-2.1.9\objs\ftccache.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftccache.c): redefinition of FTC_Cache_RemoveFaceID ignored
Warning! W1027: file freetype-2.1.9\objs\ftccmap.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftccmap.c): redefinition of FTC_CMapCache_New ignored
Warning! W1027: file freetype-2.1.9\objs\ftccmap.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftccmap.c): redefinition of FTC_CMapCache_Lookup ignored
Warning! W1027: file freetype-2.1.9\objs\ftccmap.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftccmap.c): redefinition of ftc_cmap_cache_class ignored
Warning! W1027: file freetype-2.1.9\objs\ftcglyph.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcglyph.c): redefinition of FTC_GNode_Init ignored
Warning! W1027: file freetype-2.1.9\objs\ftcglyph.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcglyph.c): redefinition of FTC_GNode_UnselectFamily ignored
Warning! W1027: file freetype-2.1.9\objs\ftcglyph.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcglyph.c): redefinition of FTC_GNode_Done ignored
Warning! W1027: file freetype-2.1.9\objs\ftcglyph.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcglyph.c): redefinition of FTC_GNode_Compare ignored
Warning! W1027: file freetype-2.1.9\objs\ftcglyph.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcglyph.c): redefinition of FTC_Family_Init ignored
Warning! W1027: file freetype-2.1.9\objs\ftcglyph.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcglyph.c): redefinition of FTC_GCache_Init ignored
Warning! W1027: file freetype-2.1.9\objs\ftcglyph.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcglyph.c): redefinition of FTC_GCache_Done ignored
Warning! W1027: file freetype-2.1.9\objs\ftcglyph.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcglyph.c): redefinition of FTC_GCache_New ignored
Warning! W1027: file freetype-2.1.9\objs\ftcglyph.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcglyph.c): redefinition of FTC_GCache_Lookup ignored
Warning! W1027: file freetype-2.1.9\objs\ftcimage.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcimage.c): redefinition of FTC_INode_Free ignored
Warning! W1027: file freetype-2.1.9\objs\ftcimage.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcimage.c): redefinition of FTC_INode_New ignored
Warning! W1027: file freetype-2.1.9\objs\ftcimage.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcimage.c): redefinition of FTC_INode_Weight ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmanag.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmanag.c): redefinition of FTC_Manager_LookupSize ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmanag.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmanag.c): redefinition of FTC_Manager_LookupFace ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmanag.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmanag.c): redefinition of FTC_Manager_New ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmanag.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmanag.c): redefinition of FTC_Manager_Done ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmanag.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmanag.c): redefinition of FTC_Manager_Reset ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmanag.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmanag.c): redefinition of FTC_Manager_Compress ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmanag.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmanag.c): redefinition of FTC_Manager_RegisterCache ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmanag.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmanag.c): redefinition of FTC_Manager_FlushN ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmanag.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmanag.c): redefinition of FTC_Manager_RemoveFaceID ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmanag.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmanag.c): redefinition of FTC_Node_Unref ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmanag.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmanag.c): redefinition of ftc_size_list_class ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmanag.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmanag.c): redefinition of ftc_face_list_class ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmru.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmru.c): redefinition of FTC_MruNode_Prepend ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmru.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmru.c): redefinition of FTC_MruNode_Up ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmru.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmru.c): redefinition of FTC_MruNode_Remove ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmru.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmru.c): redefinition of FTC_MruList_Init ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmru.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmru.c): redefinition of FTC_MruList_Reset ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmru.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmru.c): redefinition of FTC_MruList_Done ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmru.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmru.c): redefinition of FTC_MruList_Find ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmru.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmru.c): redefinition of FTC_MruList_New ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmru.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmru.c): redefinition of FTC_MruList_Lookup ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmru.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmru.c): redefinition of FTC_MruList_Remove ignored
Warning! W1027: file freetype-2.1.9\objs\ftcmru.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcmru.c): redefinition of FTC_MruList_RemoveSelection ignored
Warning! W1027: file freetype-2.1.9\objs\ftcsbits.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcsbits.c): redefinition of FTC_SNode_Free ignored
Warning! W1027: file freetype-2.1.9\objs\ftcsbits.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcsbits.c): redefinition of FTC_SNode_New ignored
Warning! W1027: file freetype-2.1.9\objs\ftcsbits.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcsbits.c): redefinition of FTC_SNode_Weight ignored
Warning! W1027: file freetype-2.1.9\objs\ftcsbits.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cache\ftcsbits.c): redefinition of FTC_SNode_Compare ignored
Warning! W1027: file freetype-2.1.9\objs\ftdbgmem.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftdbgmem.c): redefinition of _debug_mem_dummy ignored
Warning! W1027: file freetype-2.1.9\objs\ftgloadr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftgloadr.c): redefinition of FT_GlyphLoader_New ignored
Warning! W1027: file freetype-2.1.9\objs\ftgloadr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftgloadr.c): redefinition of FT_GlyphLoader_Rewind ignored
Warning! W1027: file freetype-2.1.9\objs\ftgloadr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftgloadr.c): redefinition of FT_GlyphLoader_Reset ignored
Warning! W1027: file freetype-2.1.9\objs\ftgloadr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftgloadr.c): redefinition of FT_GlyphLoader_Done ignored
Warning! W1027: file freetype-2.1.9\objs\ftgloadr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftgloadr.c): redefinition of FT_GlyphLoader_CreateExtra ignored
Warning! W1027: file freetype-2.1.9\objs\ftgloadr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftgloadr.c): redefinition of FT_GlyphLoader_CheckPoints ignored
Warning! W1027: file freetype-2.1.9\objs\ftgloadr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftgloadr.c): redefinition of FT_GlyphLoader_CheckSubGlyphs ignored
Warning! W1027: file freetype-2.1.9\objs\ftgloadr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftgloadr.c): redefinition of FT_GlyphLoader_Prepare ignored
Warning! W1027: file freetype-2.1.9\objs\ftgloadr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftgloadr.c): redefinition of FT_GlyphLoader_Add ignored
Warning! W1027: file freetype-2.1.9\objs\ftgloadr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftgloadr.c): redefinition of FT_GlyphLoader_CopyPoints ignored
Warning! W1027: file freetype-2.1.9\objs\ftgzip.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\ftgzip.c): redefinition of adler32 ignored
Warning! W1027: file freetype-2.1.9\objs\ftnames.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftnames.c): redefinition of FT_Get_Sfnt_Name_Count ignored
Warning! W1027: file freetype-2.1.9\objs\ftnames.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftnames.c): redefinition of FT_Get_Sfnt_Name ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of ft_service_list_lookup ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of ft_validator_init ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of ft_validator_run ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of ft_validator_error ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Stream_New ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Stream_Free ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of ft_glyphslot_free_bitmap ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of ft_glyphslot_set_bitmap ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of ft_glyphslot_alloc_bitmap ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_New_GlyphSlot ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Done_GlyphSlot ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Set_Transform ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Load_Glyph ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Load_Char ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_New_Face ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_New_Memory_Face ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Open_Face ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Attach_File ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Attach_Stream ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Done_Face ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_New_Size ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Done_Size ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Set_Char_Size ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Set_Pixel_Sizes ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Get_Kerning ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Select_Charmap ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Set_Charmap ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Get_Charmap_Index ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_CMap_Done ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_CMap_New ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Get_Char_Index ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Get_First_Char ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Get_Next_Char ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Get_Name_Index ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Get_Glyph_Name ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Get_Postscript_Name ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Get_Sfnt_Table ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Load_Sfnt_Table ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Get_CMap_Language_ID ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Activate_Size ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Lookup_Renderer ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Get_Renderer ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Set_Renderer ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Render_Glyph_Internal ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Render_Glyph ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Add_Module ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Get_Module ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Get_Module_Interface ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of ft_module_get_service ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Remove_Module ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_New_Library ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Library_Version ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Done_Library ignored
Warning! W1027: file freetype-2.1.9\objs\ftobjs.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftobjs.c): redefinition of FT_Set_Debug_Hook ignored
Warning! W1027: file freetype-2.1.9\objs\ftoutln.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftoutln.c): redefinition of FT_Outline_Decompose ignored
Warning! W1027: file freetype-2.1.9\objs\ftoutln.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftoutln.c): redefinition of FT_Outline_New_Internal ignored
Warning! W1027: file freetype-2.1.9\objs\ftoutln.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftoutln.c): redefinition of FT_Outline_New ignored
Warning! W1027: file freetype-2.1.9\objs\ftoutln.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftoutln.c): redefinition of FT_Outline_Check ignored
Warning! W1027: file freetype-2.1.9\objs\ftoutln.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftoutln.c): redefinition of FT_Outline_Copy ignored
Warning! W1027: file freetype-2.1.9\objs\ftoutln.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftoutln.c): redefinition of FT_Outline_Done_Internal ignored
Warning! W1027: file freetype-2.1.9\objs\ftoutln.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftoutln.c): redefinition of FT_Outline_Done ignored
Warning! W1027: file freetype-2.1.9\objs\ftoutln.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftoutln.c): redefinition of FT_Outline_Get_CBox ignored
Warning! W1027: file freetype-2.1.9\objs\ftoutln.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftoutln.c): redefinition of FT_Outline_Translate ignored
Warning! W1027: file freetype-2.1.9\objs\ftoutln.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftoutln.c): redefinition of FT_Outline_Reverse ignored
Warning! W1027: file freetype-2.1.9\objs\ftoutln.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftoutln.c): redefinition of FT_Outline_Render ignored
Warning! W1027: file freetype-2.1.9\objs\ftoutln.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftoutln.c): redefinition of FT_Outline_Get_Bitmap ignored
Warning! W1027: file freetype-2.1.9\objs\ftoutln.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftoutln.c): redefinition of FT_Vector_Transform ignored
Warning! W1027: file freetype-2.1.9\objs\ftoutln.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftoutln.c): redefinition of FT_Outline_Transform ignored
Warning! W1027: file freetype-2.1.9\objs\ftoutln.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftoutln.c): redefinition of FT_Outline_Get_Orientation ignored
Warning! W1027: file freetype-2.1.9\objs\ftrfork.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftrfork.c): redefinition of FT_Raccess_Get_HeaderInfo ignored
Warning! W1027: file freetype-2.1.9\objs\ftrfork.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftrfork.c): redefinition of FT_Raccess_Get_DataOffsets ignored
Warning! W1027: file freetype-2.1.9\objs\ftrfork.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftrfork.c): redefinition of FT_Raccess_Guess ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_OpenMemory ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_Close ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_Seek ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_Skip ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_Pos ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_Read ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_ReadAt ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_ExtractFrame ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_ReleaseFrame ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_EnterFrame ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_ExitFrame ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_GetChar ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_GetShort ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_GetShortLE ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_GetOffset ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_GetLong ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_GetLongLE ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_ReadChar ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_ReadShort ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_ReadShortLE ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_ReadOffset ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_ReadLong ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_ReadLongLE ignored
Warning! W1027: file freetype-2.1.9\objs\ftstream.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftstream.c): redefinition of FT_Stream_ReadFields ignored
Warning! W1027: file freetype-2.1.9\objs\fttrigon.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\fttrigon.c): redefinition of FT_Cos ignored
Warning! W1027: file freetype-2.1.9\objs\fttrigon.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\fttrigon.c): redefinition of FT_Sin ignored
Warning! W1027: file freetype-2.1.9\objs\fttrigon.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\fttrigon.c): redefinition of FT_Tan ignored
Warning! W1027: file freetype-2.1.9\objs\fttrigon.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\fttrigon.c): redefinition of FT_Atan2 ignored
Warning! W1027: file freetype-2.1.9\objs\fttrigon.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\fttrigon.c): redefinition of FT_Vector_Unit ignored
Warning! W1027: file freetype-2.1.9\objs\fttrigon.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\fttrigon.c): redefinition of FT_Vector_Rotate ignored
Warning! W1027: file freetype-2.1.9\objs\fttrigon.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\fttrigon.c): redefinition of FT_Vector_Length ignored
Warning! W1027: file freetype-2.1.9\objs\fttrigon.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\fttrigon.c): redefinition of FT_Vector_Polarize ignored
Warning! W1027: file freetype-2.1.9\objs\fttrigon.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\fttrigon.c): redefinition of FT_Vector_From_Polar ignored
Warning! W1027: file freetype-2.1.9\objs\fttrigon.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\fttrigon.c): redefinition of FT_Angle_Diff ignored
Warning! W1027: file freetype-2.1.9\objs\ftutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftutil.c): redefinition of FT_Alloc ignored
Warning! W1027: file freetype-2.1.9\objs\ftutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftutil.c): redefinition of FT_QAlloc ignored
Warning! W1027: file freetype-2.1.9\objs\ftutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftutil.c): redefinition of FT_Realloc ignored
Warning! W1027: file freetype-2.1.9\objs\ftutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftutil.c): redefinition of FT_QRealloc ignored
Warning! W1027: file freetype-2.1.9\objs\ftutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftutil.c): redefinition of FT_Free ignored
Warning! W1027: file freetype-2.1.9\objs\ftutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftutil.c): redefinition of FT_List_Find ignored
Warning! W1027: file freetype-2.1.9\objs\ftutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftutil.c): redefinition of FT_List_Add ignored
Warning! W1027: file freetype-2.1.9\objs\ftutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftutil.c): redefinition of FT_List_Insert ignored
Warning! W1027: file freetype-2.1.9\objs\ftutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftutil.c): redefinition of FT_List_Remove ignored
Warning! W1027: file freetype-2.1.9\objs\ftutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftutil.c): redefinition of FT_List_Up ignored
Warning! W1027: file freetype-2.1.9\objs\ftutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftutil.c): redefinition of FT_List_Iterate ignored
Warning! W1027: file freetype-2.1.9\objs\ftutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\base\ftutil.c): redefinition of FT_List_Finalize ignored
Warning! W1027: file freetype-2.1.9\objs\infblock.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\infblock.c): redefinition of inflate_blocks_reset ignored
Warning! W1027: file freetype-2.1.9\objs\infblock.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\infblock.c): redefinition of inflate_blocks_new ignored
Warning! W1027: file freetype-2.1.9\objs\infblock.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\infblock.c): redefinition of inflate_blocks ignored
Warning! W1027: file freetype-2.1.9\objs\infblock.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\infblock.c): redefinition of inflate_blocks_free ignored
Warning! W1027: file freetype-2.1.9\objs\infblock.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\infblock.c): redefinition of inflate_mask ignored
Warning! W1027: file freetype-2.1.9\objs\infblock.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\infblock.c): redefinition of border ignored
Warning! W1027: file freetype-2.1.9\objs\infcodes.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\infcodes.c): redefinition of inflate_codes_new ignored
Warning! W1027: file freetype-2.1.9\objs\infcodes.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\infcodes.c): redefinition of inflate_codes ignored
Warning! W1027: file freetype-2.1.9\objs\infcodes.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\infcodes.c): redefinition of inflate_codes_free ignored
Warning! W1027: file freetype-2.1.9\objs\infcodes.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\infcodes.c): redefinition of inflate_mask ignored
Warning! W1027: file freetype-2.1.9\objs\inflate.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inflate.c): redefinition of inflateReset ignored
Warning! W1027: file freetype-2.1.9\objs\inflate.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inflate.c): redefinition of inflateEnd ignored
Warning! W1027: file freetype-2.1.9\objs\inflate.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inflate.c): redefinition of inflateInit2_ ignored
Warning! W1027: file freetype-2.1.9\objs\inflate.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inflate.c): redefinition of inflate ignored
Warning! W1027: file freetype-2.1.9\objs\inftrees.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inftrees.c): redefinition of huft_build ignored
Warning! W1027: file freetype-2.1.9\objs\inftrees.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inftrees.c): redefinition of inflate_trees_bits ignored
Warning! W1027: file freetype-2.1.9\objs\inftrees.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inftrees.c): redefinition of inflate_trees_dynamic ignored
Warning! W1027: file freetype-2.1.9\objs\inftrees.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inftrees.c): redefinition of inflate_trees_fixed ignored
Warning! W1027: file freetype-2.1.9\objs\inftrees.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inftrees.c): redefinition of cplens ignored
Warning! W1027: file freetype-2.1.9\objs\inftrees.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inftrees.c): redefinition of cplext ignored
Warning! W1027: file freetype-2.1.9\objs\inftrees.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inftrees.c): redefinition of cpdist ignored
Warning! W1027: file freetype-2.1.9\objs\inftrees.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inftrees.c): redefinition of cpdext ignored
Warning! W1027: file freetype-2.1.9\objs\inftrees.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inftrees.c): redefinition of fixed_bl ignored
Warning! W1027: file freetype-2.1.9\objs\inftrees.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inftrees.c): redefinition of fixed_bd ignored
Warning! W1027: file freetype-2.1.9\objs\inftrees.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inftrees.c): redefinition of fixed_tl ignored
Warning! W1027: file freetype-2.1.9\objs\inftrees.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\inftrees.c): redefinition of fixed_td ignored
Warning! W1027: file freetype-2.1.9\objs\infutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\infutil.c): redefinition of inflate_flush ignored
Warning! W1027: file freetype-2.1.9\objs\infutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\infutil.c): redefinition of inflate_mask ignored
Warning! W1027: file freetype-2.1.9\objs\pcfdrivr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\pcf\pcfdrivr.c): redefinition of pcf_cmap_class ignored
Warning! W1027: file freetype-2.1.9\objs\pcfdrivr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\pcf\pcfdrivr.c): redefinition of pcf_driver_class ignored
Warning! W1027: file freetype-2.1.9\objs\pfrcmap.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\pfr\pfrcmap.c): redefinition of pfr_cmap_class_rec ignored
Warning! W1027: file freetype-2.1.9\objs\pfrdrivr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\pfr\pfrdrivr.c): redefinition of pfr_metrics_service_rec ignored
Warning! W1027: file freetype-2.1.9\objs\pfrdrivr.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\pfr\pfrdrivr.c): redefinition of pfr_driver_class ignored
Warning! W1027: file freetype-2.1.9\objs\psauxmod.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\psaux\psauxmod.c): redefinition of ps_table_funcs ignored
Warning! W1027: file freetype-2.1.9\objs\psauxmod.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\psaux\psauxmod.c): redefinition of ps_parser_funcs ignored
Warning! W1027: file freetype-2.1.9\objs\psauxmod.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\psaux\psauxmod.c): redefinition of t1_builder_funcs ignored
Warning! W1027: file freetype-2.1.9\objs\psauxmod.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\psaux\psauxmod.c): redefinition of t1_decoder_funcs ignored
Warning! W1027: file freetype-2.1.9\objs\psauxmod.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\psaux\psauxmod.c): redefinition of t1_cmap_classes ignored
Warning! W1027: file freetype-2.1.9\objs\psauxmod.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\psaux\psauxmod.c): redefinition of psaux_module_class ignored
Warning! W1027: file freetype-2.1.9\objs\pshinter.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\pshinter\pshinter.c): redefinition of ps_hints_apply ignored
Warning! W1027: file freetype-2.1.9\objs\pshmod.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\pshinter\pshmod.c): redefinition of pshinter_module_class ignored
Warning! W1027: file freetype-2.1.9\objs\psnames.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\psnames\psnames.c): redefinition of psnames_module_class ignored
Warning! W1027: file freetype-2.1.9\objs\raster.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\raster\raster.c): redefinition of ft_standard_raster ignored
Warning! W1027: file freetype-2.1.9\objs\raster.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\raster\raster.c): redefinition of ft_raster1_renderer_class ignored
Warning! W1027: file freetype-2.1.9\objs\raster.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\raster\raster.c): redefinition of ft_raster5_renderer_class ignored
Warning! W1027: file freetype-2.1.9\objs\sfnt.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\sfnt\sfnt.c): redefinition of sfnt_module_class ignored
Warning! W1027: file freetype-2.1.9\objs\smooth.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\smooth\smooth.c): redefinition of gray_raster_render ignored
Warning! W1027: file freetype-2.1.9\objs\smooth.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\smooth\smooth.c): redefinition of ft_grays_raster ignored
Warning! W1027: file freetype-2.1.9\objs\smooth.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\smooth\smooth.c): redefinition of ft_smooth_renderer_class ignored
Warning! W1027: file freetype-2.1.9\objs\smooth.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\smooth\smooth.c): redefinition of ft_smooth_lcd_renderer_class ignored
Warning! W1027: file freetype-2.1.9\objs\smooth.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\smooth\smooth.c): redefinition of ft_smooth_lcdv_renderer_class ignored
Warning! W1027: file freetype-2.1.9\objs\t1cmap.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\psaux\t1cmap.c): redefinition of t1_cmap_standard_class_rec ignored
Warning! W1027: file freetype-2.1.9\objs\t1cmap.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\psaux\t1cmap.c): redefinition of t1_cmap_expert_class_rec ignored
Warning! W1027: file freetype-2.1.9\objs\t1cmap.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\psaux\t1cmap.c): redefinition of t1_cmap_custom_class_rec ignored
Warning! W1027: file freetype-2.1.9\objs\t1cmap.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\psaux\t1cmap.c): redefinition of t1_cmap_unicode_class_rec ignored
Warning! W1027: file freetype-2.1.9\objs\ttcmap0.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\sfnt\ttcmap0.c): redefinition of tt_cmap0_class_rec ignored
Warning! W1027: file freetype-2.1.9\objs\ttcmap0.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\sfnt\ttcmap0.c): redefinition of tt_cmap2_class_rec ignored
Warning! W1027: file freetype-2.1.9\objs\ttcmap0.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\sfnt\ttcmap0.c): redefinition of tt_cmap4_class_rec ignored
Warning! W1027: file freetype-2.1.9\objs\ttcmap0.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\sfnt\ttcmap0.c): redefinition of tt_cmap6_class_rec ignored
Warning! W1027: file freetype-2.1.9\objs\ttcmap0.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\sfnt\ttcmap0.c): redefinition of tt_cmap8_class_rec ignored
Warning! W1027: file freetype-2.1.9\objs\ttcmap0.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\sfnt\ttcmap0.c): redefinition of tt_cmap10_class_rec ignored
Warning! W1027: file freetype-2.1.9\objs\ttcmap0.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\sfnt\ttcmap0.c): redefinition of tt_cmap12_class_rec ignored
Warning! W1027: file freetype-2.1.9\objs\ttdriver.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\truetype\ttdriver.c): redefinition of tt_driver_class ignored
Warning! W1027: file freetype-2.1.9\objs\ttsbit.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\sfnt\ttsbit.c): redefinition of sbit_metrics_fields ignored
Warning! W1027: file freetype-2.1.9\objs\type1.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\type1\type1.c): redefinition of t1_driver_class ignored
Warning! W1027: file freetype-2.1.9\objs\type1cid.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\cid\type1cid.c): redefinition of t1cid_driver_class ignored
Warning! W1027: file freetype-2.1.9\objs\type42.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\type42\type42.c): redefinition of t42_driver_class ignored
Warning! W1027: file freetype-2.1.9\objs\zutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\zutil.c): redefinition of zcalloc ignored
Warning! W1027: file freetype-2.1.9\objs\zutil.obj(C:\sdl_ttf-2.0.6\freetype-2.1.9\src\gzip\zutil.c): redefinition of zcfree ignored
searching libraries
Error! E2028: ft_memcpy is an undefined reference
Error! E2028: inflate_fast is an undefined reference
Error! E2028: FT_UNUSED is an undefined reference
creating map file
creating an OS/2 and eComStation dynamic link library
